CREATE TABLE USUARIO(
	CPF CHAR(11) NOT NULL,
	NOME VARCHAR(50) DEFAULT NULL,
	RG CHAR(9) NOT NULL, 
	ENDEREÇO VARCHAR(100) DEFAULT NULL,
	DATA_NASC DATE DEFAULT NULL,
	PRIMARY KEY(CPF)
);

CREATE TABLE MOTORISTA(
	CPF_MOTORISTA CHAR(11) NOT NULL,
	CNH CHAR(9) NOT NULL,
	CONTA INT NOT NULL,
	PRIMARY KEY(CPF_MOTORISTA),
	CONSTRAINT MOTORISTA_ibfk_1 FOREIGN KEY (CPF_MOTORISTA) REFERENCES USUARIO (CPF) ON UPDATE CASCADE
);

CREATE TABLE PASSAGEIRO(
	CPF_PASSAGEIRO CHAR(11) NOT NULL,	
	CART_CREDT INT NOT NULL,
	PRIMARY KEY(CPF_PASSAGEIRO),
	CONSTRAINT PASSAGEIRO_ibfk_1  FOREIGN KEY (CPF_PASSAGEIRO) REFERENCES USUARIO (CPF) ON UPDATE CASCADE
);

CREATE TABLE ATENDENTE(
	CPF_ATENDENTE CHAR(11) NOT NULL, 
	FORM_ESCOLAR VARCHAR(50) NOT NULL,
	PRIMARY KEY(CPF_ATENDENTE),
	CONSTRAINT ATENDENTE_ibfk_1 FOREIGN KEY (CPF_ATENDENTE) REFERENCES USUARIO (CPF) ON UPDATE CASCADE
);

CREATE TABLE VEICULO (
	RENAVAM INT NOT NULL, 
	DATA_COMPRA DATE DEFAULT NULL, 
	MARCA VARCHAR(50) NOT NULL, 
	MODELO VARCHAR(50) NOT NULL,  
	ANO DATE NOT NULL,  
	PRECO FLOAT DEFAULT NULL,
	CARACTERISTICA VARCHAR(50) NOT NULL, 
	CPF_MOTORISTA CHAR(11) NOT NULL,
	PRIMARY KEY(RENAVAM),
	CONSTRAINT VEICULO_ibfk_1 FOREIGN KEY (CPF_MOTORISTA) REFERENCES MOTORISTA (CPF_MOTORISTA) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT CLASSIFICACAO_CK CHECK ( CARACTERISTICA IN('econômico', 'SUV', 'luxo', 'rural'))
);

CREATE TABLE SEGURADORA(
	CNPJ CHAR(14) NOT NULL, 
	NOME VARCHAR(50) NOT NULL, 
	TELEFONE VARCHAR(50) NOT NULL,
	END_POSTAL INT NOT NULL,
	PRIMARY KEY(CNPJ)
);

CREATE TABLE ASSEGURA(
	RENAVAM INT NOT NULL,  
	CNPJ_SEGURADORA CHAR(14) NOT NULL,
	NUMERO_APOLICE INT NOT NULL, 
	VALOR_APOLICE FLOAT NOT NULL,
	PRIMARY KEY(RENAVAM),
	CONSTRAINT VEICULO_ibfk_1 FOREIGN KEY (RENAVAM) REFERENCES VEICULO (RENAVAM) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT VEICULO_ibfk_2 FOREIGN KEY (CNPJ_SEGURADORA) REFERENCES SEGURADORA (CNPJ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE HISTORICO_CORRIDAS(
	NUM_CORRIDA INT NOT NULL, 
	CPF_PASSAGEIRO_RESPONSAVEL CHAR(11) NOT NULL, 
	CPF_MOTORISTA CHAR(11) NOT NULL, 
	ENDE_DESTINO VARCHAR(100) NOT NULL, 
	DATA_INICIO DATE NOT NULL, 
	DATA_FIM DATE NOT NULL, 
	HORA_INICIO TIME NOT NULL, 
	HORA_FIM TIME NOT NULL, 
	VALOR_TOTAL FLOAT NOT NULL,
	PRIMARY KEY(NUM_CORRIDA, CPF_PASSAGEIRO_RESPONSAVEL),
    CONSTRAINT HISTORICO_CORRIDAS_ibfk_1 FOREIGN KEY (CPF_MOTORISTA) REFERENCES MOTORISTA (CPF_MOTORISTA) ON UPDATE CASCADE,
	CONSTRAINT HISTORICO_CORRIDAS_ibfk_2 FOREIGN KEY (CPF_PASSAGEIRO_RESPONSAVEL) REFERENCES PASSAGEIRO (CPF_PASSAGEIRO) ON UPDATE CASCADE
);

CREATE TABLE CARONANTES_CORRIDA(
	NUM_CORRIDA INT NOT NULL, 
	CPF_PASSAGEIRO_RESPONSAVEL CHAR(11) NOT NULL,
	CPF_PASSAGEIRO_CARONANTE CHAR(11) NOT NULL,
	PRIMARY KEY(NUM_CORRIDA, CPF_PASSAGEIRO_RESPONSAVEL, CPF_PASSAGEIRO_CARONANTE),
	CONSTRAINT CARONANTES_CORRIDA_ibfk_1 FOREIGN KEY (NUM_CORRIDA,CPF_PASSAGEIRO_RESPONSAVEL) REFERENCES HISTORICO_CORRIDAS (NUM_CORRIDA, CPF_PASSAGEIRO_RESPONSAVEL) ON UPDATE CASCADE,
	CONSTRAINT CARONANTES_CORRIDA_ibfk_2 FOREIGN KEY (CPF_PASSAGEIRO_CARONANTE) REFERENCES PASSAGEIRO (CPF_PASSAGEIRO) ON UPDATE CASCADE
);

CREATE TABLE ATENDENTE_CORRIDA(
	NUM_CORRIDA INT NOT NULL, 
	CPF_PASSAGEIRO_RESPONSAVEL CHAR(11) NOT NULL,
	CPF_ATENDENTE CHAR(11) NOT NULL,
	PRIMARY KEY(NUM_CORRIDA, CPF_PASSAGEIRO_RESPONSAVEL),
	CONSTRAINT ATENDENTE_CORRIDA_ibfk_1 FOREIGN KEY (NUM_CORRIDA,CPF_PASSAGEIRO_RESPONSAVEL) REFERENCES HISTORICO_CORRIDAS (NUM_CORRIDA, CPF_PASSAGEIRO_RESPONSAVEL) ON UPDATE CASCADE,
	CONSTRAINT ATENDENTE_CORRIDA_ibfk_2 FOREIGN KEY (CPF_ATENDENTE) REFERENCES ATENDENTE (CPF_ATENDENTE) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CONVERSA(
    NUM_CORRIDA INT NOT NULL, 
    CPF_PASSAGEIRO_RESPONSAVEL CHAR(11) NOT NULL,
    NUMERO_SEQ INT NOT NULL, 
    TXT_PERGUNTA VARCHAR(200) NOT NULL,
    TXT_RESPOSTA VARCHAR(200) NOT NULL,
    PRIMARY KEY(NUM_CORRIDA, CPF_PASSAGEIRO_RESPONSAVEL, NUMERO_SEQ),
    CONSTRAINT ATENDENTE_CORRIDA_ibfk_1 FOREIGN KEY (NUM_CORRIDA,CPF_PASSAGEIRO_RESPONSAVEL) REFERENCES HISTORICO_CORRIDAS (NUM_CORRIDA, CPF_PASSAGEIRO_RESPONSAVEL) ON UPDATE CASCADE
);


