1. Dado uma seguradora, identificar quais são os veículos com seguros sob sua
responsabilidade e listar as vigências das apólices. OK
SELECT CNPJ_SEGURADORA, RENAVAM, NUMERO_APOLICE FROM ASSEGURA WHERE CNPJ_SEGURADORA = '12345678901' 

2. Dado um atendente, descobrir se ele já usou o serviço de corridas e quando. OK
SELECT NUM_CORRIDA, DATA_INICIO FROM HISTORICO_CORRIDAS WHERE  NUM_CORRIDA IN (SELECT NUM_CORRIDA FROM CARONANTES_CORRIDA WHERE  CPF_PASSAGEIRO_RESPONSAVEL =  '123456789'  OR CPF_PASSAGEIRO_CARONANTE  =  '123456789')

3. Listar quais foram os passageiros que nunca fizeram uma corrida. OK
(SELECT P.CPF_PASSAGEIRO 
FROM PASSAGEIRO AS P LEFT JOIN CARONANTES_CORRIDA AS C ON P.CPF_PASSAGEIRO = C.CPF_PASSAGEIRO_RESPONSAVEL 
 WHERE C.NUM_CORRIDA IS NULL ) 
 UNION 
(SELECT P.CPF_PASSAGEIRO FROM PASSAGEIRO AS P LEFT JOIN CARONANTES_CORRIDA AS C ON P.CPF_PASSAGEIRO = C.CPF_PASSAGEIRO_CARONANTE 
 WHERE C.NUM_CORRIDA IS NULL ) 

SELECT CPF_PASSAGEIRO, CART_CREDT
FROM PASSAGEIRO
WHERE CPF_PASSAGEIRO NOT IN (
    SELECT CPF_PASSAGEIRO_RESPONSAVEL
    FROM HISTORICO_CORRIDAS
    UNION
    SELECT CPF_PASSAGEIRO_RESPONSAVEL
    FROM CARONANTES_CORRIDA
)
AND CPF_PASSAGEIRO NOT IN (
    SELECT CPF_PASSAGEIRO_CARONANTE
    FROM CARONANTES_CORRIDA
);

4. Dado uma corrida, listar todas as perguntas e respostas feitas ao atendente responsável. OK
SELECT TXT_PERGUNTA,TXT_RESPOSTA FROM CONVERSA WHERE NUM_CORRIDA = 1001 AND CPF_PASSAGEIRO_RESPONSAVEL = '123456789'
 obs: n sei se vai assim ou só com o numero de corrida

5. Duas perguntas que o grupo julgar relevante para os requisitos.
5 .1 Dado um motorista listar todas as corridas OK 
SELECT * FROM HISTORICO_CORRIDAS WHERE CPF_MOTORISTA = '987654321'


5.2 Dado o cpf de um motorista, listar todos os seus veículos OK
SELECT * FROM VEICULO WHERE CPF_MOTORISTA = CPF
5.3 Dado uma data, listar todas as corridas OK
SELECT * FROM HISTORICO_CORRIDAS WHERE DATA_INICIO = '2023-06-04'


